org: teresashellvin
app: aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  basePath: /my-base-path/stuff
  region: us-east-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-2:188362000616:table/dynamocloud

functions:
  hello:
    handler: src/hello.handler
    events:
      - httpApi:
          path: /
          method: get
  fillin:
    handler: src/fillin.handler
    events:
      - httpApi:
          path: /stuff
          method: post
  espectaculo:
    handler: src/espectaculo.handler
    events:
      - httpApi:
          path: /stuff
          method: get
  finalizar:
    handler: src/finalizar.handler
    events:
      - httpApi:
          path: /stuff/{id}
          method: put

resources:
  Resources:
    dynamocloud:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: dynamocloud
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

            
